This code is used to tabulate our Monkeytype scores

In [ ]:
names  = ['Commander', 'BigIth', 'Jefe', 'Climber', 'Shire', 'LittleIth', 'Macrus']
fingers = [(80,1), (104,0.99), (106,1), (90,0.97), (40,1), (98,0.96), (None,None)]
thumbs = [(44,1),(58,0.95), (60,1), (None,None), (25,0.98), (None,None), (None,None)]

In [2]:
scores = {}
for name, fscore, thscore in zip(names, fingers, thumbs):
    scores[name] = {'fingers':fscore, 'thumbs':thscore}

In [3]:
import pandas as pd

scores_df = pd.DataFrame(scores).T
scores_df

                fingers        thumbs
Commander       (80, 1)       (44, 1)
BigIth       (98, 0.98)    (58, 0.95)
Jefe           (106, 1)  (None, None)
Climber      (90, 0.97)  (None, None)
Shire           (40, 1)    (25, 0.98)
LittleIth    (98, 0.96)  (None, None)
Macrus     (None, None)  (None, None)

In [4]:
scores_df['finger_score'] = scores_df.fingers.apply(lambda x: x[0])
scores_df['adj_finger_score'] = scores_df.fingers.apply(lambda x: x[0]*(2*x[1]-1) if x[0] is not None else None)
scores_df['thumb_score'] = scores_df.thumbs.apply(lambda x: x[0])
scores_df['adj_thumb_score'] = scores_df.thumbs.apply(lambda x: x[0]*(2*x[1]-1) if x[0] is not None else None)

In [5]:

scores_df.drop(columns=['fingers', 'thumbs']).sort_values(by='adj_finger_score', ascending=False)

           finger_score  adj_finger_score  thumb_score  adj_thumb_score
Jefe              106.0            106.00          NaN              NaN
BigIth             98.0             94.08         58.0             52.2
LittleIth          98.0             90.16          NaN              NaN
Climber            90.0             84.60          NaN              NaN
Commander          80.0             80.00         44.0             44.0
Shire              40.0             40.00         25.0             24.0
Macrus              NaN               NaN          NaN              NaN