This code is used to tabulate our Monkeytype scores

In [9]:
names  = ['Commander', 'BigIth', 'Jefe', 'Climber', 'Shire', 'LittleIth', 'Macrus']
fingers = [(94,1), (104,0.99), (106,1), (107,0.98), (40,1), (98,0.96), (None,None)]
thumbs = [(44,1),(58,0.95), (60,1), (None,None), (25,0.98), (None,None), (None,None)]

In [10]:
scores = {}
for name, fscore, thscore in zip(names, fingers, thumbs):
    scores[name] = {'fingers':fscore, 'thumbs':thscore}

In [11]:
import pandas as pd

scores_df = pd.DataFrame(scores).T
scores_df

                fingers        thumbs
Commander       (94, 1)       (44, 1)
BigIth      (104, 0.99)    (58, 0.95)
Jefe           (106, 1)       (60, 1)
Climber     (107, 0.98)  (None, None)
Shire           (40, 1)    (25, 0.98)
LittleIth    (98, 0.96)  (None, None)
Macrus     (None, None)  (None, None)

In [12]:
scores_df['finger_speed (wpm)'] = scores_df.fingers.apply(lambda x: x[0])
scores_df['finger acc. (%)'] = scores_df.fingers.apply(lambda x: int(x[1]*100) if x[1] is not None else None)
scores_df['adj_finger_speed (wpm)'] = scores_df.fingers.apply(lambda x: x[0]*(2*x[1]-1) if x[0] is not None else None)
scores_df['thumb_speed (wpm)'] = scores_df.thumbs.apply(lambda x: x[0])
scores_df['thumb acc. (%)'] = scores_df.thumbs.apply(lambda x: x[1]*100 if x[1] is not None else None)
scores_df['adj_thumb_speed (wpm)'] = scores_df.thumbs.apply(lambda x: x[0]*(2*x[1]-1) if x[0] is not None else None)

In [13]:

scores_df.drop(columns=['fingers', 'thumbs']).sort_values(by='adj_finger_speed (wpm)', ascending=False)

,finger_speed (wpm),finger acc. (%),adj_finger_speed (wpm),thumb_speed (wpm),thumb acc. (%),adj_thumb_speed (wpm)
Jefe,106.0,100.0,106.00,60.0,100.0,60.0
Climber,107.0,98.0,102.72,NaN,NaN,NaN
BigIth,104.0,99.0,101.92,58.0,95.0,52.2
Commander,94.0,100.0,94.00,44.0,100.0,44.0
LittleIth,98.0,96.0,90.16,NaN,NaN,NaN
Shire,40.0,100.0,40.00,25.0,98.0,24.0
Macrus,NaN,NaN,NaN,NaN,NaN,NaN